### ISSUE TITLE
Add pangrams for other languages

### ISSUE THREAD

**Issue by m-bartlett** [m-bartlett/pangram-programs#1]

**Comment by ajratnam** [comment]
@m-bartlett I find this challenge interesting,
Can I add the stuff you missed out, and perhaps even the new stuff from python 3.10 which releases on Oct 4?

**Comment by m-bartlett** [comment]
@ajratnam yes feel free! I would recommend isolating it in a way that makes sense to you from the existing python pangram, e.g. renaming the python/ dir to python3.9/ and adding python3.10/, or using `python/all-keywords-builtins-operators-3.10/`, whatever feels best to you.

**Comment by ajratnam** [comment]
Yes! Sure, I will start off by adding a few things you missed in 3.9 and then I shall add the new 3.10 features in a different file.
